# Server configuration
server.port=8080
spring.application.name=shareit

# JPA configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# SQL initialization
spring.sql.init.mode=always

# Logging configuration
logging.level.ru.practicum.shareit=DEBUG